In [9]:
import numpy as np
data = [1,2,3,4,5,6]
arr=np.array(data)
if 10 in arr:
    print("Yes! there is 2 in it.")
else:
    print("There is no 2 in it.")

There is no 2 in it.


In [ ]:
arr=np.ones((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
arr1=np.full((4,4),2)
print(arr1)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
